UserLogin/Controllers/ReceptionistController.cs
using Microsoft.AspNetCore.Mvc;

namespace UserLogin.Controllers
{
    public class ReceptionistController : Controller
    {
        // GET: ReceptionistsController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ReceptionistsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ReceptionistsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReceptionistsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReceptionistsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ReceptionistsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReceptionistsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ReceptionistsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

UserLogin/Views/Receptionist/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Receptionist Dashboard";
}
<div class="cointainer">
    <!--Diaplay tempdatamessages if they exist-->
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }
    <div style="position:absolute;top: 10px;right:10px">
        <a href="@Url.Action("Logout", "Receptionist")" class="btn btn-danger">Logout</a>
    </div>
</div>